#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#

set -e

printf "⏳ Loading context data "

curl -s -o /dev/null -X POST \
    'http://orion:1026/v2/entities/' \
    -H 'Content-Type: application/json' \
    -g -d '{
        "id": "urn:ngsi-ld:Company:001",
        "type": "Company",
        "address": {
            "type": "PostalAddress",
            "value": {
                "streetAddress": "Campus de Elviña - Facultade de Informatica",
                "addressRegion": "A Coruña",
                "addressLocality": "A Coruña",
                "postalCode": "15008"
            }
        },
        "location": {
            "type": "geo:json",
            "value": {
                "type": "Point",
                "coordinates": [43.33364650443242, -8.409320061203504]
            }
        },
        "name": {
            "type": "Text",
            "value": "Facultade de Informática"
        }
    }'

curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -g -d '{
  "actionType": "append",
  "entities": [
    {
    	"type": "Room",
    	"id": "urn:ngsi-ld:Room:001",
    	"refStore": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Company:001"
            },

    	"name": {
        	"type": "Text",
            "value": "Detector001"
    	}
    },
    {
    	"type": "Room",
        "id": "urn:ngsi-ld:Room:002",
	    "refStore": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Company:001"
            },
        
    	"name": {
        	"type": "Text",
            "value": "Detector002"
    	}
    },
    {
    	"type": "Room",
        "id": "urn:ngsi-ld:Room:003",
	    "refStore": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Company:001"
            },
        
    	"name": {
        	"type": "Text",
            "value": "Detector003"
    	}
    }
  ]
}'

curl -s -o /dev/null -X POST \
  'http://iot-agent:4041/iot/services' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -g -d '{
 "services": [
   {
     "apikey":      "4jggokgpepnvsb2uv4s40d59ov",
     "cbroker":     "http://orion:1026",
     "entity_type": "Noise",
     "resource":    "/iot/d"
   },
     {
     "apikey":      "4jggokgpepnvsb2uv4s40d59ov",
     "cbroker":     "http://orion:1026",
     "entity_type": "Bluetooth",
     "resource":    "/iot/d"
   }
 ]
}'

curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -g -d '{
  "actionType": "append",
  "entities": [
    {
    	"id": "urn:ngsi-ld:Noise:001",
        "type": "Noise",
        "name": {
            "type": "Text",
            "value": "Microphone001"
        },
        "rssi": {
            "type": "Integer",
            "value": null
        },
        "refStore": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Room:001"
            }
    },
    {
    	"id": "urn:ngsi-ld:Noise:002",
        "type": "Noise",
        "name": {
            "type": "Text",
            "value": "Microphone002"
        },
        "rssi": {
            "type": "Integer",
            "value": null
        },
        "refStore": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Room:002"
            }
    },
    {
    	"id": "urn:ngsi-ld:Noise:003",
        "type": "Noise",
        "name": {
            "type": "Text",
            "value": "Microphone003"
        },
        "rssi": {
            "type": "Integer",
            "value": null
        },
        "refStore": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Room:003"
            }
    }
  ]
}'

curl -iX POST \
  'http://iot-agent:4041/iot/devices' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "devices": [
   {
     "device_id":   "noise001",
     "entity_name": "urn:ngsi-ld:Noise:001",
     "entity_type": "Noise",
     "attributes": [
      { "object_id": "rssi", "name": "rssi", "type": "Integer" }
     ],
     "static_attributes": [
       { "name":"refStore", "type": "Relationship", "value": "urn:ngsi-ld:Room:001"}
     ]
   },
   {
     "device_id":   "noise002",
     "entity_name": "urn:ngsi-ld:Noise:002",
     "entity_type": "Noise",
     "attributes": [
       { "object_id": "rssi", "name": "rssi", "type": "Integer" }
     ],
     "static_attributes": [
       { "name":"refStore", "type": "Relationship", "value": "urn:ngsi-ld:Room:002"}
     ]
   },
   {
     "device_id":   "noise003",
     "entity_name": "urn:ngsi-ld:Noise:003",
     "entity_type": "Noise",
     "attributes": [
       { "object_id": "rssi", "name": "rssi", "type": "Integer" }
     ],
     "static_attributes": [
       { "name":"refStore", "type": "Relationship", "value": "urn:ngsi-ld:Room:003"}
     ]
   }
 ]
}
'

curl -s -o /dev/null -X POST \
  'http://orion:1026/v2/op/update' \
  -H 'Content-Type: application/json' \
  -g -d '{
  "actionType": "append",
  "entities": [
    {
        "id": "urn:ngsi-ld:Bluetooth:001",
        "type": "Bluetooth",
        "name": {
                "type": "Text",
                "value": "Bluetooth001"
        },
        "refStore": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Room:001"
            }
    },
    {
        "id": "urn:ngsi-ld:Bluetooth:002",
        "type": "Bluetooth",
        "name": {
                "type": "Text",
                "value": "Bluetooth002"
        },
        "refStore": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Room:002"
            }
    },
    {
        "id": "urn:ngsi-ld:Bluetooth:003",
        "type": "Bluetooth",
        "name": {
                "type": "Text",
                "value": "Bluetooth003"
        },
        "refStore": {
                "type": "Relationship",
                "value": "urn:ngsi-ld:Room:003"
            }
    }
  ]
}'

curl -iX POST \
  'http://iot-agent:4041/iot/devices' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
 "devices": [
   {
     "device_id":   "bluetooth001",
     "entity_name": "urn:ngsi-ld:Bluetooth:001",
     "entity_type": "Bluetooth",
     "attributes": [
      { "object_id": "rssi", "name": "rssi", "type": "Integer" }
     ],
     "static_attributes": [
       { "name":"refStore", "type": "Relationship", "value": "urn:ngsi-ld:Room:001"}
     ]
   },
   {
     "device_id":   "bluetooth002",
     "entity_name": "urn:ngsi-ld:Bluetooth:002",
     "entity_type": "Bluetooth",
     "attributes": [
       { "object_id": "rssi", "name": "rssi", "type": "Integer" }
     ],
     "static_attributes": [
       { "name":"refStore", "type": "Relationship", "value": "urn:ngsi-ld:Room:002"}
     ]
   },
   {
     "device_id":   "bluetooth003",
     "entity_name": "urn:ngsi-ld:Bluetooth:003",
     "entity_type": "Bluetooth",
     "attributes": [
       { "object_id": "rssi", "name": "rssi", "type": "Integer" }
     ],
     "static_attributes": [
       { "name":"refStore", "type": "Relationship", "value": "urn:ngsi-ld:Room:003"}
     ]
   }
 ]
}
'

echo -e " \033[1;32mdone\033[0m"
